version: '3.9'

services:

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: microservice_ressource
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
    volumes:
      - db_mysql:/var/lib/mysql   # Persister les données de la BD entre tous les conteneurs 
      #- C:/xampp/mysql/data:/var/lib/mysql   #persister les données avec bd locale  et j'enleve volumes vers la fin 


  eureka-server:
    build: ./Eureka
    image: yosrba/eureka:1.0
    container_name: eureka
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  configServer:
    build: ./configServer_
    image: yosrba/config:1.0
    container_name: config
    ports:
      - "8888:8888"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 5s
      timeout: 3s
      retries: 10
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/


  ressource:
    build: ./Ressource
    image: yosrba/ressource:1.0
    container_name: ressource
    ports:
      - "8082:8082"
    depends_on:
      db:
        condition: service_healthy
      eureka-server:
        condition: service_started
      configServer:
        condition: service_started
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - spring.datasource.url=jdbc:mysql://db:3306/microservice_ressource?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&max_allowed_packet=15728640
      - spring.datasource.username=root
      - spring.datasource.password=root

  API-gateway:
    build: ./ApiGetWay
    image: yosrba/apigetway:1.0
    container_name: apigetway
    ports:
      - "8090:8090"
    depends_on:
      - eureka-server
      - ressource
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/


  departementService:
    build: ./departement
    image: yosrba/departementservice:1.1
    container_name: departementService
    ports:
      - "8089:8089"
    depends_on:
      db:
        condition: service_healthy
      eureka-server:
        condition: service_started
      configServer:
        condition: service_started
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/departementService?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&max_allowed_packet=15728640
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - spring.datasource.username=root
      - spring.datasource.password=root

  formation:
    build: ./formation  # Path to your Spring Boot project
    image: yosrba/formation:1.0
    container_name: formation
    ports:
      - "8083:8083"  # Expose the Spring Boot application on port 8089
    depends_on:
      db:
        condition: service_healthy
      eureka-server:
        condition: service_started
      configServer:
        condition: service_started
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/formation?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&max_allowed_packet=15728640
      - spring.datasource.username=root
      - spring.datasource.password=root

volumes:
  db_mysql: